### ISSUE TITLE
Samples:Grove Kit is lacking information

### ISSUE THREAD

**Issue by gpaes** [solettaproject/soletta#1583]
#### Task Description
The Samples:Grove Kit page (https://github.com/solettaproject/soletta/wiki/Samples:Grove-Kit) is lacking information about the samples:

- [x] It would be nice to have an introduction about what the samples are about and a link to the Grove Kit itself 
- [x] There must be a link to the source code/flow of each sample
- [x] There must be an explanation about what each sample do
- [x] There must be an explanation about the pins, the person might not use the pictured board to test the sample
- [x] Order samples by their complexity, from simplest to most complex

#### Dependencies
None

**Comment by mbelluzzo** [comment]
@gpaes, I kind of understood what you mean by "explanation about the pins", but independently of having a picture or not, because the pins don't need to be that exactly ones and that many pins have the needed capability, It would be insane to list everywhere: "you could use any pin from x to y", specially when there are holes. It also changes from board to board and we won't have pictures for every board.

**Comment by barbieri** [comment]
We must describe based on our example, not the possibilities. You can say why it was chosen and how user could find an alternative.

**Comment by mbelluzzo** [comment]
But that is already different in each config file

**Comment by gpaes** [comment]
@mbelluzzo Can't we do an explanation based on @barbieri approach? That's what I was aiming for with that task.

**Comment by mbelluzzo** [comment]
As I answered him, the pins are already different between config files of the same sample for different boards. I think is going a little too far on silly details, inside the config itself it says type: pwm for example, pin 5, why? it has pwm support, obvious. type gpio, pin: 10, why, has gpio, what is the alternative? any other pin that makes you happy that supports gpio. Is that simple.

**Comment by gpaes** [comment]
@mbelluzzo Yes, they are different for each config file. Is it too much to explain "this is connected to a pwm pin" / "this is connected to gpio" and so on? Won't this be a nice information to have stated along the example?

**Comment by mbelluzzo** [comment]
To explain that is a pwm on a pwm pin is implied on the sample explanation. To explain the alternatives and why a given pin was chosen (not pin type, iow pin 3 instead of pwm pin) as it was suggested, not.

**Comment by edersondisouza** [comment]
On 05-04-2016 13:41, Murilo Belluzzo wrote:
> To explain that is a pwm on a pwm pin is implied on the sample
> explanation. To explain the alternatives and why a given pin was chosen
> (not pin type, iow pin 3 instead of pwm pin) as it was suggested, not.

Maybe all that is necessary is to explain something like:

"Here you see that sensors are connected to the same pins used on fbp 
samples. You may want to choose them, to any compatible pin - but 
remember to change fbp code accordingly"

?

**Comment by mbelluzzo** [comment]
+2 on only add this disclaimer after sample explanation.

**Comment by gpaes** [comment]
@edersondisouza @mbelluzzo That makes sense:)
