### ISSUE TITLE
MinnowBoard MAX Instructions: Improve page links

### ISSUE THREAD

**Issue by gpaes** [solettaproject/soletta#1621]
#### Task Description
Page: https://github.com/solettaproject/soletta/wiki/MinnowBoard-MAX-Instructions
There are a couple of links missing and some links that being added will help the person reading the document.

- [x] Replace “point to a doc/tutorial here” at the beginning of the page with a proper link to a document or tutorial about Yocto
- [x] Replace "bitbake requirements (e.g. python2)" with a link to bitbake's official page that states which are its requirements
- [x] Add link to the Intel layer (like it's being done to the Soletta layer)
- [x] Add link to the poky layer (like it's being done to the Soletta layer)

#### Dependencies
None
