### ISSUE TITLE
Presentations: Improve page usage

### ISSUE THREAD

**Issue by gpaes** [solettaproject/soletta#1623]
#### Task Description
Page: https://github.com/solettaproject/soletta/wiki/Presentations
Currently the page has only one entry and it is not working.
This page is meant to be both an archive of past presentations and a schedule of future ones.

- [x] Add a brief explanation of the purpose of this page
- [x] Add working links to the existing event, both to lhc.net.br and to the said PDF
- [x] Add entries for all the past Soletta events that we already had
- [x] Add entries for all the upcoming Soletta events that are already scheduled

#### Dependencies
None

**Comment by gpaes** [comment]
@bdilly Pretty nice!!
