### ISSUE TITLE
API Changes: Sol-Arena

### ISSUE THREAD

**Issue by cabelitos** [solettaproject/soletta#1659]
#### Task Description

In order to keep our API consistent with soletta's style, some changes are required in Sol-Arena.

- [ ] Rename `sol_arena_strndup()` to `sol_arena_str_dup_n()`  (Tip: Use `sed` for this one, for more info type `man sed` in your terminal)
- [ ] In `sol_arena_slice_dup_str_n()` rename the `str` argument to `src`.
- [ ] In `sol_arena_slice_dup_str()` rename the `str` argument to `src`.
- [ ] In `sol_arena_slice_dup()` rename the `slice` argument to `src`.

#### Dependencies
None.

**Comment by amandawrcoelho** [comment]
@ceolin we can close this :)
