### ISSUE TITLE
API Changes: Sol_vector and Sol_ptr_vector

### ISSUE THREAD

**Issue by cabelitos** [solettaproject/soletta#1662]
#### Task Description

- [ ] Rename `sol_ptr_vector_get_nocheck()`/`sol_vector_get_nocheck()` to `sol_ptr_vector_get_no_check()`/`sol_vector_get_no_check()`
- [ ] In `sol_ptr_vector_match_first()` rename the `elem` parameter to `template`
- [ ] Rename all functions that containts `take` keyword to `steal`. Example: `sol_vector_take_data()` should be `sol_vector_steal_data()`
- [ ] `sol_ptr_vector_find_last()`/`sol_ptr_vector_find_first()` should return an `int32_t` type. 

#### Dependencies

None.

**Comment by ceolin** [comment]
fixed
