### ISSUE TITLE
API Changes: Sol-json

### ISSUE THREAD

**Issue by cabelitos** [solettaproject/soletta#1667]
#### Task Description

- [ ] `Rename sol_json_scanner_skip_over()` to `sol_json_scanner_skip()`
- [ ] Replace `unsigned int` to `size_t` in the following functions (Return values and/or argument):
* `sol_json_scanner_init()`
* `sol_json_scanner_get_size_remaining()`
* `sol_json_scanner_get_mem_offset()`
* `sol_json_token_get_size()`
* `sol_json_token_str_eq()`
- [ ] Rename `sol_json_loop_helper_*()` functions to `sol_json_loop_iterate_*()`
- [ ] Rename `enum sol_json_loop_reason` to `enum sol_json_loop_status`
- [ ] Loop macros - Rename `end_reason` argument to `status`
- [ ] Rename the following macros:
* `SOL_JSON_SCANNER_ARRAY_LOOP_NEST()` to `SOL_JSON_SCANNER_ARRAY_LOOP_TYPE_NESTED()`
* `SOL_JSON_SCANNER_ARRAY_LOOP()` to `SOL_JSON_SCANNER_ARRAY_LOOP_TYPE()`
* `SOL_JSON_SCANNER_ARRAY_LOOP_ALL_NEST()` to `SOL_JSON_SCANNER_ARRAY_LOOP_NESTED()`
* `SOL_JSON_SCANNER_ARRAY_LOOP_ALL()` to `SOL_JSON_SCANNER_ARRAY_LOOP()`
* `SOL_JSON_SCANNER_OBJECT_LOOP_NEST()` to `SOL_JSON_SCANNER_OBJECT_LOOP_NESTED()`

- [ ] Bonus: Split json docs in sections

#### Dependencies

None

**Comment by amandawrcoelho** [comment]
I'm working on it.
