### ISSUE TITLE
API Changes: Sol_Mainloop

### ISSUE THREAD

**Issue by cabelitos** [solettaproject/soletta#1668]
#### Task Description
- [ ] Rename `sol_args_set()` to `sol_set_args()`
- [ ] Rename `sol_mainloop_source_add()` to `sol_mainloop_add_source()`
- [ ] Rename `sol_mainloop_source_del()` to `sol_mainloop_del_source()`
- [ ] Rename `SOL_SET_API_VERSION()` argument  (`x`) to `expression`

#### Dependencies
None.
