### ISSUE TITLE
API Changes: Sol-types

### ISSUE THREAD

**Issue by cabelitos** [solettaproject/soletta#1669]
#### Task Description

- [ ] Rename `SOL_BUFFER_TYPE_NOFREE` to `SOL_BUFFER_TYPE_NO_FREE`
- [ ] Move `sol_drange_val_equal()` to sol-util.c and call it `sol_util_double_equal()`
- [ ] Rename `sol_*_addition()` to `sol_*_add()`
- [ ] Rename `sol_*_division()` to `sol_*_div()`
- [ ] Rename `sol_*_modulo()` to `sol_*_mod()`
- [ ] Rename `sol_*_multiplication()` to `sol_*_mul()`
- [ ] Rename `sol_*_subtraction()` to `sol_*_sub()`

#### Dependencies

None

**Comment by amandawrcoelho** [comment]
@ceolin we can close this task
