### ISSUE TITLE
API Changes: Sol-Macros

### ISSUE THREAD

**Issue by cabelitos** [solettaproject/soletta#1674]
#### Task Description

- [ ] Rename `SOL_ATTR_NORETURN` to `SOL_ATTR_NO_RETURN`
- [ ] Rename `SOL_ATTR_NONNULL` to `SOL_ATTR_NON_NULL`
- [ ] Rename `SOL_ATTR_NOINSTRUMENT` to `SOL_ATTR_NO_INSTRUMENT`
- [ ] Rename section @ doxygen - sol-macros to sol compiler macros

#### Dependencies
None.

**Comment by amandawrcoelho** [comment]
@ceolin we can close this task
