### ISSUE TITLE
API Changes: Sol-platform

### ISSUE THREAD

**Issue by cabelitos** [solettaproject/soletta#1675]
#### Task Description

- [ ] Remove macros `CHUNK_READ_SIZE`, `CHUNK_READ_MAX` and `CHUNK_MAX_TIME_NS` from the header. They should not be exported
- [ ] Rename `SOL_PLATFORM_TARGET_POWEROFF` to `SOL_PLATFORM_TARGET_POWER_OFF`
- [ ] The function `sol_platform_get_state()` should return an `enum sol_platform_state` and not an `int`

#### Dependencies
None.

**Comment by amandawrcoelho** [comment]
@ceolin we can close this :)
