### ISSUE TITLE
API Changes: Flow

### ISSUE THREAD

**Issue by bdilly** [solettaproject/soletta#1677]
#### Task Description

 - [x] use unit8_t instead of unsigned char for byte representation
 - [x] send_location_packet miss function receiving components, just like rgb and direction_vector does
 - [x] rename `sol_flow_builder_export_in_port()` to `sol_flow_builder_export_port_in()` (the same applies for export_out_port
 - [x] rename `sol_flow_packet_get_packet_type_as_string()` to `sol_flow_get_packet_type_name()`
 - [ ] function read_file() on struct sol_flow_parser_client should use sol_buffer
 - [ ] `sol_flow_parse_buffer_metatype()` should use sol_buffer too
 - [x] `sol_flow_simplectype_event` struct should be renamed to `sol_flow_simple_c_type_event`
 - [x] `sol_flow_simplectype_*` should be `sol_flow_simple_c_type` in the whole API
 - [x] `sol_flow_single_port_in_connect()` should be `sol_flow_single_connect_port_in()` (same applies for disconnect and the remaining of API).

**Comment by nirmalsinghania2008** [comment]
is it uint8_t or unit8_t?
unit8_t is included in stdint.h
i am working on it assuming it is uint8_t

**Comment by kaspersky** [comment]
#2061

**Comment by kaspersky** [comment]
#2155

**Comment by ceolin** [comment]
done
