### ISSUE TITLE
API Changes: LWM2M

### ISSUE THREAD

**Issue by cabelitos** [solettaproject/soletta#1688]
#### Task Description

- [x] Do not use typedefs.
- [x] Document what's a TLV 
- [x] Rename `sol_lwm2m_client_info_get_sms()` to `sol_lwm2m_client_info_get_sms_number()`
- [x] Rename `sol_lwm2m_notify_observers()` to `sol_lwm2m_client_notify()`
- [x] Rename `sol_lwm2m_send_update()` to `sol_lwm2m_client_send_update()`
- [x] `sol_lwm2m_tlv_get_bytes()` should receive a `struct sol_buffer` as argument
- [x] Rename `sol_lwm2m_tlv_array_clear()` to `sol_lwm2m_tlv_list_clear()`
- [x] Rename `sol_lwm2m_tlv_to_bool()`, `sol_lwm2m_tlv_to_int()`... and so on to
`sol_lwm2m_tlv_get_bool()`, `sol_lwm2m_tlv_get_int()` ...
- [x] Rename `sol_lwm2m_server_management_write()` to `sol_lwm2m_server_write()`
- [x] Rename `sol_lwm2m_server_management_read()` to `sol_lwm2m_server_read()`
- [x] Rename `sol_lwm2m_server_management_delete` to `sol_lwm2m_server_delete_object_instance()`
- [x] Rename `sol_lwm2m_server_management_execute()` to `sol_lwm2m_server_execute_resource()`
- [x] Rename `sol_lwm2m_server_management_create` to `sol_lwm2m_server_create_object_instance()`

#### Dependencies
None.

**Comment by bsmelo** [comment]
I believe this is closed, isn't it? :-)

**Comment by cabelitos** [comment]
@bsmelo Indeed. Closing
