### ISSUE TITLE
API Changes: Sol-network

### ISSUE THREAD

**Issue by cabelitos** [solettaproject/soletta#1716]
#### Task Description
- [ ] Rename `SOL_INET_ADDR_STRLEN` to `SOL_NETWORK_INET_ADDR_STR_LEN`
- [ ] Rename `sol_network_hostname_handle` to `sol_network_hostname_pending`
- [ ] Rename `sol_network_cancel_get_hostname_address_info()` to `sol_network_hostname_pending_cancel()`
- [ ] Functions `sol_network_link_down()`, `sol_network_link_up()`, `sol_network_unsubscribe_events()` and `sol_network_subscribe_events()` should return an `int` instead of `bool`. Where `0` (zero) means success  and on error `-errno` should be returned.

#### Dependencies
None.

**Comment by amandawrcoelho** [comment]
@ceolin we can close this task
