### ISSUE TITLE
API Changes: HTTP

### ISSUE THREAD

**Issue by cabelitos** [solettaproject/soletta#1717]
#### Task Description
- [ ] Rename `sol_http_param_add()` to `sol_http_params_add()` (the same for `sol_http_param_add_copy()`)
- [ ] Functions `sol_http_param_add()` and `sol_http_param_add_copy()` should return an `int` instead of `bool`. Where `0` (zero) means success  and on error `-errno` should be returned.
- [ ] Rename `sol_http_create_simple_uri_from_str()` to `sol_http_create_uri_from_str()`
- [ ] Rename `sol_http_create_simple_uri()` to `sol_http_create_uri()`
- [ ] Rename `sol_http_create_uri()` to `sol_http_create_full_uri()`

#### Dependencies
None

**Comment by amandawrcoelho** [comment]
@ceolin  we can close this :)
