### ISSUE TITLE
API Changes: Mavlink

### ISSUE THREAD

**Issue by cabelitos** [solettaproject/soletta#1719]
#### Task Description
- [ ]  `SOL_MAVLINK_MODE_ATTITUDE` -> `SOL_MAVLINK_MODE_ALTITUDE`
- [ ]  `SOL_MAVLINK_MODE_AUTOTUNE` -> `SOL_MAVLINK_MODE_AUTO_TUNE`
- [ ]  `SOL_MAVLINK_MODE_POSHOLD` -> `SOL_MAVLINK_MODE_POS_HOLD`
- [ ]  `sol_mavlink_check_armed()` -> `sol_mavlink_is_armed()`
- [ ] `sol_mavlink_get_curr_position()` -> `sol_mavlink_get_current_position()`
- [ ] `sol_mavlink_goto()` -> `sol_mavlink_go_to()`
- [ ] `sol_mavlink_takeoff()` -> `sol_mavlink_take_off()`

#### Dependencies
None.

**Comment by bdilly** [comment]
done
