### ISSUE TITLE
API Changes: COAP

### ISSUE THREAD

**Issue by cabelitos** [solettaproject/soletta#1720]
#### Task Description
- [x] Remove typedefs
- [x] Replace all `CONTENTTYPE`s with `CONTENT_TYPE`. Example `SOL_COAP_CONTENTTYPE_NONE` should be `SOL_COAP_CONTENT_TYPE_NONE`
- [x] `LINKFORMAT` -> `LINK_FORMAT`
- [x] `MAKE_RSPCODE` -> `sol_coap_make_response_code()`
- [x] Replace `RSPCODE` with `RESPONSE_CODE`
- [x] `responsecode` -> `response_code`
- [x] `SOL_COAP_TYPE_NONCON` -> `SOL_COAP_TYPE_NON_CON`
- [x] Use `size_t` for sizes instead of `uint16_t` - Examples - `sol_coap_add_option()` argument `len` should be a size_t
- [x] `sol_coap_header_set_ver()` -> `sol_coap_header_set_version()`
- [x] `sol_coap_header_get_ver()` -> `sol_coap_header_get_version()`
- [x] `sol_coap_packet_notification_new()` -> `sol_coap_packet_new_notification()`
- [x] `sol_coap_packet_request_new()` -> `sol_coap_packet_new_request()`
- [x] `sol_coap_unobserve_server()` -> `sol_coap_unobserve_by_token()`
- [x] `sol_coap_uri_path_to_buf()` -> `sol_coap_path_to_buffer()`
- [ ] Remove `sol_coap_secure_server_new()` and `sol_coap_server_new()` should receive a `bool` argument that flags if the server is secure or not

#### Dependencies
None.

**Comment by otaviobp** [comment]
most of tasks fixed in #2024 
Assigning to @ceolin because he is working in last issue

**Comment by cabelitos** [comment]
We're leaving the sizes as `uint16_t`
The last issue (`sol_coap_secure_server`) is fixed in https://github.com/solettaproject/soletta/pull/2185

**Comment by cabelitos** [comment]
merged
