### ISSUE TITLE
API Changes: OIC

### ISSUE THREAD

**Issue by cabelitos** [solettaproject/soletta#1721]
#### Task Description
- [ ] Remove `int:0` from `struct sol_oic_platform_information`
- [ ] `struct sol_oic_platform_information` -> `struct sol_oic_platform_info`
- [ ] Use `int64_t` for `system_time` in `struct sol_oic_platform_information`
- [ ] Remove `int:0` from `struct sol_oic_server_information`
- [ ] `struct sol_oic_server_information` -> `struct sol_oic_device_info`
- [ ] Documents the fields of `struct sol_oic_map_reader`
- [ ] `enum sol_oic_map_loop_reason` -> `enum sol_oic_map_loop_status`
- [ ] `href` -> `path` in `struct sol_oic_resource`
- [ ] `is_observing` -> `is_observed` in `struct sol_oic_resource`
- [ ] `sol_oic_notify_observers()` -> `sol_oic_server_notify_observers()`
- [ ] The macros `OIC_PLATFORM_ID`, `OIC_MANUFACTURER_NAME` and so on, should be set using Kconfig (make menuconfig)
- [ ] Functions that return `bool` - return type should be changed to `int` and they should return `0` (zero) on success and `-errno` on error.
- [ ] First callback parameter should be the user's data.

#### Dependencies
None.
