### ISSUE TITLE
PinMux: Improve page text

### ISSUE THREAD

**Issue by gpaes** [solettaproject/soletta#1731]
#### Task Description
Page: https://github.com/solettaproject/soletta/wiki/PinMux
On the introduction elaborate more on why this solution is needed: the introduction doesn't really talk clearly about the pinmux.
The body text could also be expanded and some examples added to make it clear what we're talking about.

- [x] Improve introduction to talk more clearly on the pinmux solution
- [x] Expand the text to add more details to each topic
- [x] Add examples to the text to help people to understand what is being discussed

#### Dependencies
None
