### ISSUE TITLE
API Changes: AIO / I2C

### ISSUE THREAD

**Issue by bdilly** [solettaproject/soletta#1741]
#### Task Description

Some changes are required to match [Soletta's API design conventions](https://github.com/solettaproject/soletta/wiki/API-design-conventions)

 - [ ] use is_busy instead of just busy to highlight the query. So `sol_aio_is_busy()` instead of `sol_aio_busy()`. The same applies for `sol_i2c_busy()`.
 - [ ] `sol_i2c_bus_get()` -> `sol_i2c_get_bus()`
 - [ ] change return type of functions that may fail to return error code instead of boolean `false`. Example: `sol_i2c_set_slave_address()`

**Comment by bdilly** [comment]
looks like only the second item is missing, the others seem to be done already
