### ISSUE TITLE
Porting: Improve "tl;dr" section

### ISSUE THREAD

**Issue by gpaes** [solettaproject/soletta#1745]
#### Task Description
Page: https://github.com/solettaproject/soletta/wiki/Porting#tldr
Before the bullet list add a brief text explaining what the list is about.
Consider renaming it to "Quick Overview" if such renaming makes sense.

- [ ] Add brief text to "tl;dr" section
- [ ] Consider renaming the "td;dr" section to "Quick Overview" or something like that if such renaming makes sense
- [ ] If section is renamed make sure that no link is left broken

#### Dependencies
None

**Comment by bdilly** [comment]
I won't rename the section, tl;dr is fine imo but just below it's explained it's about a quick overview and explain what is the list about.

done
