### ISSUE TITLE
API Changes: PWM

### ISSUE THREAD

**Issue by bdilly** [solettaproject/soletta#1753]
#### Task Description

Some changes are required to match [Soletta's API design conventions](https://github.com/solettaproject/soletta/wiki/API-design-conventions)

 - [ ] Some structs are missing a "@brief" command
 - [ ] Change return type of functions that may fail to return error code instead of boolean `false`. Example: `sol_pwm_get_enabled()`
 - [ ] Rename `sol_pwm_get_enabled()` to `sol_pwm_is_enabled()`

**Comment by ceolin** [comment]
https://github.com/solettaproject/soletta/commit/fc2ac5dcd6afa05137b5d4f6486379e34d87dc62
