### ISSUE TITLE
API Changes: SPI

### ISSUE THREAD

**Issue by bdilly** [solettaproject/soletta#1754]
#### Task Description

Some changes are required to match [Soletta's API design conventions](https://github.com/solettaproject/soletta/wiki/API-design-conventions)

 - [x] Some structs are missing "@brief" doxygen command
 - [ ] Use `sol_buffer` on `sol_spi_transfer()`
 - [x] Change return type of functions that may fail to return error code instead of boolean `false`. 
 - [ ] Create API for read / write

**Comment by cabelitos** [comment]
* Creating read/write API does not makes sense for SPI.
* Using sol_buffers is not a good option in here, because it will make the API too complicated.
