### ISSUE TITLE
API Changes: UART

### ISSUE THREAD

**Issue by bdilly** [solettaproject/soletta#1755]
#### Task Description

Some changes are required to match [Soletta's API design conventions](https://github.com/solettaproject/soletta/wiki/API-design-conventions)

 - [ ] Some structs are missing "@brief" doxygen command
 - [x] Change return type of functions that may fail to return error code instead of boolean `false`. 
 - [ ] Create API for read - check if it's doable something like sol_socket read / write . Add API to check if it can write / read
 - [ ] Read callback is called 1 byte a time (it would be better to add ways to receive more data) - check feasibility.
 - [ ] Review the remaining API to check if it's consistent with other I/O API. It's way the most divergent one.

**Comment by cabelitos** [comment]
#2050
