### ISSUE TITLE
API Changes: MemMap

### ISSUE THREAD

**Issue by bdilly** [solettaproject/soletta#1756]
#### Task Description

Some changes are required to match [Soletta's API design conventions](https://github.com/solettaproject/soletta/wiki/API-design-conventions)

 - [ ] Some structs are missing "@brief" doxygen command
 - [ ] Static functions are missing docs, as `sol_memmap_read_uint8()`
 - [ ] Change return type of functions that may fail to return error code instead of boolean `false`. 
 - [ ] `MEMMAP_VERSION_ENTRY` macro should be `SOL_MEMMAP_VERSION_ENTRY`

**Comment by ceolin** [comment]
fixed
