### ISSUE TITLE
Create new wiki page: Soletta on flow based programming

### ISSUE THREAD

**Issue by gpaes** [solettaproject/soletta#1765]
#### Task Description
Page to be created: https://github.com/solettaproject/soletta/wiki/Soletta-on-flow-based-programming
This page will hold an introduction to Soletta, how it deals with flow based programming and how to do FBP on it.
This page will be the starting point for Soletta on FBP and will as such will concentrate the FBP-related links that currently are on the Documentation page: Logic constructs on Soletta flows, Strings on Soletta flows, JSON on Soletta flows, HTTP on Soletta flows, Testing with Soletta flows and Configuration File Naming and Search Paths -- adding a brief text that explains what we're going to find inside each page.

- [ ] Create **Soletta on flow based programming** page
- [ ] In this new page add an introductory text to Soletta and FBP: how it deals with it and how to do programs in it
- [ ] Add FBP-related links that currently are on **Documentation**: **Logic constructs on Soletta flows**, **Strings on Soletta flows**, **JSON on Soletta flows**, **HTTP on Soletta flows**, **Testing with Soletta flows** and **Configuration File Naming and Search Paths** -- adding a brief text that explains what we're going to find inside each page
- [ ] Add a link to **Soletta on flow based programming** in the wiki's **right side menu**

#### Dependencies
None
