### ISSUE TITLE
API Changes: Review Comms API looking for convergence

### ISSUE THREAD

**Issue by bdilly** [solettaproject/soletta#1820]
#### Task Description

It would be nice to review all communication API and try to make they all look the same.

They should be async, callbacks should pass data pointer as first parameter, etc

But also they should look similar. E.g:
 * if in a protocol you add elements one by one using _add(*element) and other add an array of elements you should go with the same for both - if possible
 * if you initialized some modules instances passing a config and in others set config with a specific call

Go through all headers on `src/lib/comms/include/` and be happy

Missing items:

- [x] On sol-http-client.h (and maybe others), use the new ``SOL_REENTRANT()`` thing to avoid comments in the doc like "don't do X at context Y".
- [x] On sol-lwm2m.h, maybe use blob on ``sol_lwm2m_resource_init()`` and friends, so that we're more flexible WRT the life cicle of the resource's payload memory (we would unref the blob internally)
- [x] Also on LWM2M, maybe the contexts involving ``sol_lwm2m_parse_tlv()`` should deal with a buffer instead of a slice

**Comment by cabelitos** [comment]
The http-client code is already safe. Ignore the first missing item. I'm only creating a PR that update the docs.

https://github.com/solettaproject/soletta/pull/2191

**Comment by cabelitos** [comment]
fixed
