### ISSUE TITLE
Meta-Soletta: Create page text

### ISSUE THREAD

**Issue by gpaes** [solettaproject/soletta#1830]
#### Task Description
Page: https://github.com/solettaproject/soletta/wiki/Meta-Soletta
Complete introductory text explaining why we have the meta-soletta layer and what's it for.
Add a section to explain that every patch to meta-soletta will be tested on ostro-ci, with the relevant links.
Talk about how it can be used with pure Yocto and also with Ostro.
Add a section to talk about Yocto and the supported boards.
Add a section to talk about Ostro and its layers and updates with links to documentation on the oficial homepage.

- [x] Complete introductory text, talking about how it can be used both with Yocto and with Ostro and how that choice (Yocto or Ostro) can influence the workflow
- [x] Explain that meta-soletta patches are tested on ostro-ci, with relevant links
- [x] Add Yocto section with links to the pages that instructs how to use **Yocto with Edison** and **Yocto with Minnowboard MAX**. Discuss how it's best to always use the Ostro layer since it brings lots of fixes and additional supported boards.
- [x] Add Ostro section discussing what's important for this activity
- [x] Update **meta-soletta/readme.md** to point to this new page

#### Dependencies
None

**Comment by brunobottazzini** [comment]
@gpaes,

Two questions here:

In a near future, our officially images will be from Ostro OS (An IoT Os that is based in Yocto and uses our meta-soletta). 

1- In that case, should we put the instructions to build only using Ostro ? What do you think @barbieri 
?

2- Their build instructions would be huge. It may confuse the user when reading it. What do you think creating different pages for each board and then pointing out a link to them ?

**Comment by gpaes** [comment]
@brunobottazzini 
1 - If the only official way is via Ostro, then yes, we would need to update the documents to talk about it only
2 - Yes, linking would be enough. We already have a link to Edison+Yocto

**Comment by gpaes** [comment]
@brunobottazzini @bdilly I updated the ticket to reflect the new information. Please verifiy if it's all correct.

**Comment by brunobottazzini** [comment]
Closing the issue...

As we both have reviewed the documentation and pushed to the master.

Thanks!!
